config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  resources :devices
devise_for :users, :controllers => { registrations: 'registrations' }

root 'dashboard#dashboard'
  get 'dashboard/help'
  get 'dashboard/terms'
  get 'dashboard/profile'
  get 'dashboard/devices'
  get 'dashboard/transactions'
  get 'dashboard/dashboard'
  get 'dashboard/vouchers'
  get 'dashboard/users'
  get 'dashboard/link_voucher'
  get 'dashboard/add_voucher'
  get 'dashboard/generate_vouchers'
  get 'dashboard/purchase_data'
  get 'dashboard/data_purchase_transaction'
  get 'dashboard/purchase_voice'
  get 'dashboard/voice_purchase_transaction'
  get 'dashboard/transfer_airtime'
  get 'dashboard/airtime_transaction'

match '/dashboard',    to: 'dashboard#dashboard',    via: 'get'
match '/profile', to: 'dashboard#profile', via: 'get'
match '/devices', to: 'dashboard#devices', via: 'get'
match '/transactions',    to: 'dashboard#transactions',    via: 'get'
match '/help',    to: 'dashboard#help',    via: 'get'
match '/terms',    to: 'dashboard#terms',    via: 'get'
match '/admin/vouchers',    to: 'dashboard#vouchers',    via: 'get'
match '/users',    to: 'dashboard#users',    via: 'get'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        #format.html { redirect_to @device, notice: 'Device was successfully created.' }
        #format.json { render :show, status: :created, location: @device }
        format.html {redirect_to root_path, notice: 'Device was successfully created.'}
        #format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        #format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        #format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        #format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      #format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      #format.json { head :no_content }
      format.html {redirect_to root_path, notice: 'Device was successfully removed.'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :token, :user_id)
    end
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :device_name %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token, id: :device_token %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :device_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Token</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.token %></td>
        <td><%= device.user_id %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Token:</strong>
  <%= @device.token %>
</p>

<p>
  <strong>User:</strong>
  <%= @device.user_id %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>