config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  resources :devices
devise_for :users, :controllers => { registrations: 'registrations' }

root 'dashboard#dashboard'
  get 'dashboard/help'
  get 'dashboard/terms'
  get 'dashboard/profile'
  get 'dashboard/devices'
  get 'dashboard/transactions'
  get 'dashboard/dashboard'
  get 'dashboard/vouchers'
  get 'dashboard/users'
  get 'dashboard/link_voucher'
  get 'dashboard/add_voucher'
  get 'dashboard/generate_vouchers'
  get 'dashboard/purchase_data'
  get 'dashboard/data_purchase_transaction'
  get 'dashboard/purchase_voice'
  get 'dashboard/voice_purchase_transaction'
  get 'dashboard/transfer_airtime'
  get 'dashboard/airtime_transaction'

match '/dashboard',    to: 'dashboard#dashboard',    via: 'get'
match '/profile', to: 'dashboard#profile', via: 'get'
match '/devices', to: 'dashboard#devices', via: 'get'
match '/transactions',    to: 'dashboard#transactions',    via: 'get'
match '/help',    to: 'dashboard#help',    via: 'get'
match '/terms',    to: 'dashboard#terms',    via: 'get'
match '/admin/vouchers',    to: 'dashboard#vouchers',    via: 'get'
match '/users',    to: 'dashboard#users',    via: 'get'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  belongs_to :user
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_action :set_voucher, only: [:show, :edit, :update, :destroy]

  # GET /vouchers
  # GET /vouchers.json
  def index
    @vouchers = Voucher.all
  end

  # GET /vouchers/1
  # GET /vouchers/1.json
  def show
  end

  # GET /vouchers/new
  def new
    @voucher = Voucher.new
  end

  # GET /vouchers/1/edit
  def edit
  end

  # POST /vouchers
  # POST /vouchers.json
  def create
    @voucher = Voucher.new(voucher_params)

    respond_to do |format|
      if @voucher.save
        #format.html { redirect_to @voucher, notice: 'Voucher was successfully created.' }
        #format.json { render :show, status: :created, location: @voucher }
        format.html { redirect_to 'dashboard/vouchers', notice: 'Voucher was successfully updated.' }
        format.json { render :show, status: :created, location: 'dashboardvouchers' }
      else
        format.html { render :new }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vouchers/1
  # PATCH/PUT /vouchers/1.json
  def update
    respond_to do |format|
      if @voucher.update(voucher_params)
        #format.html { redirect_to @voucher, notice: 'Voucher was successfully updated.' }
        #format.json { render :show, status: :ok, location: @voucher }
        format.html { redirect_to root_path, notice: 'Voucher was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vouchers/1
  # DELETE /vouchers/1.json
  def destroy
    @voucher.destroy
    respond_to do |format|
      #format.html { redirect_to vouchers_url, notice: 'Voucher was successfully destroyed.' }
      format.json { head :no_content }
      format.html { redirect_to 'dashboard/vouchers', notice: 'Voucher was successfully updated.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voucher
      @voucher = Voucher.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voucher_params
      params.require(:voucher).permit(:voucher_code, :voucher_type, :voucher_value, :voucher_value_remaining, :user_id )
    end


end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/vouchers/_form.html.erb
<%= form_with(model: voucher, local: true) do |form| %>
  <% if voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voucher.errors.count, "error") %> prohibited this voucher from being saved:</h2>

      <ul>
      <% voucher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :voucher_code %>
    <%= form.text_field :voucher_code, id: :voucher_voucher_code %>
  </div>

  <div class="field">
    <%= form.label :voucher_type %>
    <%= form.text_field :voucher_type, id: :voucher_voucher_type %>
  </div>

  <div class="field">
    <%= form.label :voucher_value %>
    <%= form.text_field :voucher_value, id: :voucher_voucher_value %>
  </div>

  <div class="field">
    <%= form.label :voucher_value_remaining %>
    <%= form.text_field :voucher_value_remaining, id: :voucher_voucher_value_remaining %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<h1>Editing Voucher</h1>

<%= render 'form', voucher: @voucher %>

<%= link_to 'Show', @voucher %> |
<%= link_to 'Back', vouchers_path %>

app/views/vouchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vouchers</h1>

<table>
  <thead>
    <tr>
      <th>Voucher code</th>
      <th>Voucher type</th>
      <th>Voucher value</th>
      <th>Voucher value remaining</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= voucher.voucher_code %></td>
        <td><%= voucher.voucher_type %></td>
        <td><%= voucher.voucher_value %></td>
        <td><%= voucher.voucher_value_remaining %></td>
        <td><%= link_to 'Show', voucher %></td>
        <td><%= link_to 'Edit', edit_voucher_path(voucher) %></td>
        <td><%= link_to 'Destroy', voucher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voucher', new_voucher_path %>

app/views/vouchers/new.html.erb
<h1>New Voucher</h1>

<%= render 'form', voucher: @voucher %>

<%= link_to 'Back', vouchers_path %>

app/views/vouchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voucher code:</strong>
  <%= @voucher.voucher_code %>
</p>

<p>
  <strong>Voucher type:</strong>
  <%= @voucher.voucher_type %>
</p>

<p>
  <strong>Voucher value:</strong>
  <%= @voucher.voucher_value %>
</p>

<p>
  <strong>Voucher value remaining:</strong>
  <%= @voucher.voucher_value_remaining %>
</p>

<%= link_to 'Edit', edit_voucher_path(@voucher) %> |
<%= link_to 'Back', vouchers_path %>